#! /bin/sh

###################
## Configuration ##
###################

## Workspace Names
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

## Common bspwm Configuration
bspc config border_width 2
bspc config window_gap 16
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config top_padding 32

## Color Settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"

# Cursor for the root window.
xsetroot -cursor_name left_ptr

##################
## Window Rules ##
##################

## Workspace 1
bspc rule -a URxvt desktop='^1' follow=on focus=on

## Workspace 2
bspc rule -a Firefox desktop='^2' follow=on focus=on

## Workspace 3
bspc rule -a keepassxc desktop='^3' follow=on focus=on

## Workspace 4

## Workspace 5

## Workspace 6

## Workspace 7

## Workspace 8
bspc rule -a Lxappearance desktop='^8' state=floating follow=on

## Must be floating.
bspc rule -a feh state=floating follow=on
bspc rule -a keepassxc state=floating follow=on
bspc rule -a Anki state=floating follow=on

################
## Auto Start ##
################

# Keybind Daemon
pkill sxhkd
sxhkd &

# System Bar
pkill lemonbar
$HOME/.config/lemonbar/lemonbar.sh &

# Wallpaper
$HOME/.config/feh/fehbg.sh &
