#! /bin/sh

###################
## Configuration ##
###################

## Workspace Names
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

## Common bspwm Configuration
bspc config border_width 2
bspc config window_gap 16
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config top_padding 48

## Color Settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"

# Cursor for the root window.
xsetroot -cursor_name left_ptr

##################
## Window Rules ##
##################

## Workspace 1 (labs)
bspc rule -a URxvt desktop='^1' follow=on focus=on

## Workspace 2 (web browsers)
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on

## Workspace 3 (file-manager)
bspc rule -a Thunar desktop='^3' follow=on focus=on

## Workspace 4 (text-editors)

## Workspace 5 (graphic-utilities)

## Workspace 6 (multimedia)

## Workspace 7 (graphics-editors)

## Workspace 8 (system-settings)
bspc rule -a Lxappearance desktop='^8' state=floating follow=on

## Must be floating.
bspc rule -a feh state=floating follow=on

################
## Auto Start ##
################

# Keybind Daemon
pkill sxhkd
sxhkd &

# System Bar
pkill lemonbar
$HOME/.config/lemonbar/lemonbar.sh &
